### PR TITLE
feat: datum by hash

### PR DESCRIPTION
**Pull request by rvcas**
Adds a new reducer and leverages projections

### CODE REVIEW

**Comment by Vardominator** [comment]
@rvcas Do you think this can be merged relatively soon?

**Comment by rvcas** [comment]
@Vardominator needs some work still. Will finish this week

**Comment by Vardominator** [comment]
@rvcas Are you still waiting for approval from @scarmuega ?

**Comment by rvcas** [comment]
this is old and I don't think it's that useful anymore?

**Pull request closed without merging**
